### ISSUE TITLE
Dynamic font-size

### ISSUE THREAD

**Issue by macglencoe** [macglencoe/EmporiumWebsite#8]
Currently, all the fonts are set by `px` and media queries. This is unnecessarily verbose, but also, less flexible.
```css
.card-name-text {
    font-size: 30px;
}
@media (max-width: 680px) {
    .card-name-text {
        font-size: 18px;
    }
}
``` 

It would solve plenty of sizing issues to use new dynamic units such as `vw`, `vh`, and `vmin`. Also try `em` and `rem`
